### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by alexbuijs** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#14]
Is it possible to get this plugin published on npm? That would make it a lot easier to keep track of updates to the plugin. Thanks!

**Comment by MadMaxedy** [comment]
@alexbuijs I took the liberty to publish it on npm myself:

https://www.npmjs.com/package/FilePicker-Phonegap-iOS-Plugin

**Comment by jcesarmobile** [comment]
@MadMaxedy can you send a PR with the package.json?

**Comment by alexbuijs** [comment]
It's probably a good idea to change the cordova id in package.json and config.xml to 'FilePicker-Phonegap-iOS-Plugin' as well (or better yet, change them and the npm name to something like 'cordova-plugin-filepicker-ios' ;-). Now cordova tries to add the plugin to the project on every prepare or build:
```
Discovered plugin "FilePicker-Phonegap-iOS-Plugin" in config.xml. Adding it to the project
Fetching plugin "FilePicker-Phonegap-iOS-Plugin@1.1.3" via npm
Plugin "com.jcesarmobile.filepicker" already installed on ios.
```

**Comment by jcesarmobile** [comment]
@MadMaxedy I've published it as `cordova-plugin-filepicker`, can you delete yours?
https://www.npmjs.com/package/cordova-plugin-filepicker

I didn't put ios on it because I plan to also add Android implementation.
And also, I plan to update the plugin to use the new iOS 11 pickers as current ones become deprecated.
