### ISSUE TITLE
Could not open file picker if the .ipa file generated from a Cordova build

### ISSUE THREAD

**Issue by JamilHijjawi** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#41]
Could not open file picker if the .ipa file generated from a Cordova build. It works if the .ipa file generated from the xCode.

How to make it works when building using cordova commands

**Comment by jcesarmobile** [comment]
The idea was to move the entitlements login to plugin.xml instead of using the hook (see https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/issues/15), but as Cordova is supposed to move from entitlement.plist files to a .entitlements file (as the plugin uses), then I'm waiting for that move and then write in that file instead of creating a new one.
Not sure when that will be implemented in Cordova, so for now you will have to build with Xcode.
