### ISSUE TITLE
Support cordova-cli 9.0.0 - requireCordovaModule deprecation

### ISSUE THREAD

**Issue by tombell** [jcesarmobile/FilePicker-Phonegap-iOS-Plugin#56]
The use of `context.requireCordovaModule` for non-cordova dependencies has been removed, and suggests you now add the dependency to the plugins `package.json` and `require`'d normally.

https://github.com/apache/cordova-lib/pull/707

**Comment by jcesarmobile** [comment]
That's used in the hook, the fix should be to just remove the whole hook and use edit-config or config-file tags to write on the entitlement plist files. I was waiting for cordova-ios 5.0.0 as it was going to use .entitlements files instead of the .plist files, but that wasn't implemented in the end and took longer than I expected.

Closing as there is another issue for that 
https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/issues/48

**Comment by tombell** [comment]
Thanks for the comment @jcesarmobile 👍

**Comment by jcesarmobile** [comment]
As an user has send a [PR](https://github.com/jcesarmobile/FilePicker-Phonegap-iOS-Plugin/pull/58) I've published 1.1.6 with the fix
Will remove the hook in a next major version
